version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day-of-month: "1"
    open-pull-requests-limit: 1
    groups:
      github_actions_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          [
            "version-update:semver-major",
            "version-update:semver-minor",
            "version-update:semver-patch",
          ]

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day-of-month: "1"
    open-pull-requests-limit: 1
    groups:
      cargo_all:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "indicatif"
        update-types: ["version-update:semver-major"]
      - dependency-name: "criterion"
        update-types: ["version-update:semver-major"]
      - dependency-name: "socket2"
        update-types: ["version-update:semver-major"]
      - dependency-name: "toml"
        update-types: ["version-update:semver-major"]
      - dependency-name: "dirs"
        update-types: ["version-update:semver-major"]
      - dependency-name: "thiserror"
        update-types: ["version-update:semver-major"]
      - dependency-name: "bincode"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prometheus"
        update-types: ["version-update:semver-major"]
